#!/bin/sh

# Downloads current installed version of youtube_dl, extracts the python module to youtube_dl/
# After that, it dumps in JSON all the data of youtube_dl

# Usage:
# ./script [YoutubeDL-executable]
# If left empty, it defaults to the standard youtube-dl

CURRENT_YOUTUBE_DL=youtube-dl

if [ ! -z "$1" ]
then
	CURRENT_YOUTUBE_DL="$1"
fi

echo Using "$CURRENT_YOUTUBE_DL" as executable 1>&2


OUTPUT_DIRECTORY=youtube_dl/
ZIP_OUTPUT="youtube-dl.zip"

####

# Extract files:

if [ ! -f extract-version.py ]
then

cat > extract-version.py <<EOF
from youtube_dl.version import __version__

print(__version__)
EOF

fi

if [ ! -f main.py ]
then

cat > main.py <<EOF
from youtube_dl.options import parseOpts
import json

(parser, _, _) = parseOpts()

for optionGroup in parser.data:
	for option in optionGroup['options']:
		if 'type' in option['named']:
			v = option['named']['type']
			# "type" cannot be encoded. Use the name of it instead.
			if isinstance(v, type):
				v = v.__name__
			option['named']['type'] = v
		# function cannot be encoded, we can just note that there is one
		if 'callback' in option['named']:
			option['named']['callback'] = True
print(json.dumps({'data': parser.data}))
EOF

fi

if [ ! -f optparse2.py ]
then

cat > optparse2.py <<EOF
# stubs for replacing optparse

SUPPRESS_HELP=None

class IndentedHelpFormatter:
	def __init__(self, **argv):
		pass

class OptionGroup:
	def __init__(self, _, name):
		self.data = { "name": name, "options": [] }
		pass

	def add_option(self, *args, **argv):
		self.data["options"].append({"positional": args, "named": argv})

class FakeOpts:
	def __init__(self):
		self.verbose = False

class OptionParser:
	def __init__(self, **argv):
		self.data = []
		pass

	def add_option_group(self, optionGroup):
		self.data.append(optionGroup.data)
		pass

	def parse_args(self, *args):
		# This is called only after last option added.
		# Dump output or do whatever :)
		return (FakeOpts(), None)
EOF

fi

####

# Extract installed youtube-dl version
VERSION_STRING="`$CURRENT_YOUTUBE_DL --version`"

# Zip file's main directory
# File name scheme changes with version
TMP_OUTPUT="youtube-dl-${VERSION_STRING}"

if [ -d "$OUTPUT_DIRECTORY" ]
then

	CURRENT_VERSION="$(python3 extract-version.py)"
	if [ "x$CURRENT_VERSION" = "x$VERSION_STRING" ]
	then
		echo Already updated. 1>&2
		python3 main.py
		exit 0
	else
		echo Versions do not match: 1>&2
		echo "$CURRENT_VERSION" 1>&2
		echo "$VERSION_STRING" 1>&2
	fi

fi

# Remove old output dir, if any
# TODO check if youtube_dl is already there, only update if the version is different
rm -rf "$OUTPUT_DIRECTORY"

# Download from releases
curl -L "https://github.com/ytdl-org/youtube-dl/archive/${VERSION_STRING}.zip" --output "${ZIP_OUTPUT}"

# Extract package, redirect output to stderr
unzip "$ZIP_OUTPUT" 1>&2
mv "$TMP_OUTPUT"/youtube_dl .

# Use our mock module instead of optparse:
# (Old config is saved at options.py.bak)
sed -i.bak 's/import optparse/import optparse2 as optparse/' youtube_dl/options.py


# Test
python3 main.py

#rm main.py optparse2.py extract-version.py
# Remove intermediate files
rm -rf "$TMP_OUTPUT"
rm "$ZIP_OUTPUT"
